// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8uiWXaHuCiOjRgYDD-sgguw7sdHZdm8',
    appId: '1:529887169763:web:8cd78977a2ad5a678249d6',
    messagingSenderId: '529887169763',
    projectId: 'giga-chat-847e1',
    authDomain: 'giga-chat-847e1.firebaseapp.com',
    storageBucket: 'giga-chat-847e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0LfGDp32dBrkGfd2h4ux1uFk30e4zPw',
    appId: '1:529887169763:android:2566b7b37f78f3cb8249d6',
    messagingSenderId: '529887169763',
    projectId: 'giga-chat-847e1',
    storageBucket: 'giga-chat-847e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddR42QrwAVZDJ0dTLcI4maylZpUZ_kFA',
    appId: '1:529887169763:ios:ede3d94977a035518249d6',
    messagingSenderId: '529887169763',
    projectId: 'giga-chat-847e1',
    storageBucket: 'giga-chat-847e1.appspot.com',
    iosClientId: '529887169763-omagb5p6k1f4vcmjof70bi2767v4kg9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddR42QrwAVZDJ0dTLcI4maylZpUZ_kFA',
    appId: '1:529887169763:ios:ecd055c65d86b2018249d6',
    messagingSenderId: '529887169763',
    projectId: 'giga-chat-847e1',
    storageBucket: 'giga-chat-847e1.appspot.com',
    iosClientId: '529887169763-3k51col9bmd80el36ukpmk0v06hhkc3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
